### ISSUE TITLE
Need to configure Tabs block

### ISSUE THREAD

**Issue by banoodle** [kanopi/gin-admin-experience#1]
The Tabs block needs to be placed in Gin's pre-content region.

It should be configured to just show secondary tabs or it will cause tab duplication on certain admin pages.

**Comment by thejimbirch** [comment]
@banoodle As discussed, we were able to identify that we could add this functionality to the `gin_primary_local_tasks` block by checking the `secondary` toggle.

We were already altering that block using config actions simple_config_update to update the region and weight.  In the latest release, 0.1.6, I added the `settings.secondary: true` alteration as shown:

```
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
        settings.secondary: true
```
Primary is also set when the block is imported, so we don't need to list it here.  We just list the things we are changing.

`settings.secondary: true` is the way to turn nested config into config actions. It looks like this in the block config file:

```
settings:
  secondary: true
```

There is a `gin_secondary_local_tasks` block that we are not importing when we run this recipe.  If we do decide that we need the secondary tabs in a different block than primary, we can remove this change, and import and set that block.
